### ISSUE TITLE
`test_draw` failing

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_workflow#523]
```python
======================================================================
ERROR: test_draw (test_node.TestNode.test_draw)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyiron_workflow/pyiron_workflow/tests/unit/test_node.py", line 346, in test_draw
    p.unlink()
  File "/home/runner/work/pyiron_workflow/pyiron_workflow/cached-miniforge/my-env/lib/python3.12/pathlib.py", line 1342, in unlink
    os.unlink(self)
IsADirectoryError: [Errno 21] Is a directory: '/home/runner/work/pyiron_workflow/pyiron_workflow/start/cached-miniforge'

----------------------------------------------------------------------
```

I looked at the offending `p.unlink()` line, and it was last touched four months ago. It looks like maybe the node's working directory is somehow getting a sub-directory stuck into it? Needs to be fixed before the next release, but doesn't seem like a burning problem. I'll look at it this week.

**Comment by liamhuber** [comment]
Problem seems to have disappeared. Since it didn't seem to start with anything we did, I'm content to let it resolve without us doing anything.
